name: CI
on:
  push:
    branches:
      - '*'
    tags: ['*']
    paths:
      - Project.yml
      - src/**
      - test/**
  pull_request:
  workflow_dispatch:
concurrency:
  # Skip intermediate builds: always.
  # Cancel intermediate builds: only if it is a pull request build.
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ startsWith(github.ref, 'refs/pull/') }}
jobs:
  test:
    name: Julia ${{ matrix.config.version }} - ${{ matrix.config.os }} - ${{ matrix.config.arch }} - ${{ github.event_name }}
    runs-on: ${{ matrix.config.os }}
    timeout-minutes: 60
    permissions: # needed to allow julia-actions/cache to proactively delete old caches that it has created
      actions: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: ubuntu-latest,  version: 'pre',  arch: 'x64'}
          - {os: ubuntu-latest,  version: '1.11',  arch: 'x64'}
          - {os: ubuntu-latest,  version: '1.10', arch: 'x64'}
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            tidyverse
            pomp
      - uses: julia-actions/setup-julia@v2
        with:
          version: ${{ matrix.config.version }}
          arch: ${{ matrix.config.arch }}
      - uses: julia-actions/cache@v2
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-runtest@v1
      - uses: julia-actions/julia-processcoverage@v1
      - uses: codecov/codecov-action@v5
        with:
          files: lcov.info
          token: ${{ secrets.CODECOV_TOKEN }}
          fail_ci_if_error: false
